# Fase 2 Limpieza de los datos

Tras unir la tabla es momento de unir datos, vamos a seguir reduciendo nulos y a eliminar columnas no deseadas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import sys
sys.path.append("../") #Para poder importar
from src.SupportCleaning import fill_organo, fill_unidad_gestora,fill_missing_organo_superior,fill_missing_organo
warnings.filterwarnings('ignore')
# Carga el dataset de trabajo
pd.set_option("display.max_columns", None) #Ver todo
df = pd.read_csv("../datos/output/datos-2013_to_2021Fase1.csv", delimiter=",",index_col=0)


# Objetivo: Reducir nulos a 0

Si es posible, ahora que hemos unido los datos, vamos a intentar sacar nuevos diccionarios que nos permita dejar todo rellenado correctamente sin nulos

In [2]:
condicion = df["código del órgano superior"].isnull()
df2 = df[condicion]
df2["nombre del órgano superior"].unique()

array([nan], dtype=object)

In [3]:
condicion = df["código del órgano"].isnull()
df2 = df[condicion]
df2["nombre del órgano"].unique()

array([nan, 'Companhia Docas do Rio Grande do Norte',
       'Controladoria-Geral da União - Unidades com vínculo direto',
       'Secretaria Especial de Agricultura Familiar e do Desenvolvimento Agrário',
       'Amazônia Azul Tecnologia de Defesa S.A.',
       'Agência Nacional de Mineração',
       'UNIVERSIDADE FEDERAL DO DELTA DO PARNAIBA',
       'TELECOMUNICACOES BRASILEIRAS S/A'], dtype=object)

In [4]:
condicion = df["código de la unidad gestora"].isnull()
df2 = df[condicion]
df2["nombre de la unidad gestora"].unique()

array([nan, 'SECRETARIA EXECUTIVA-MPA', 'SECRETARIA DE PORTOS/PR',
       'SECRETARIA DE AVIACAO CIVIL/PR',
       'FUNDO NAC.P/A CRIANCA E O ADOLESC.SET.ORC/FIN',
       'INST.FED. FLUMINENSE/CAMPUS CAMPOS-CENTRO',
       'SECRETARIA ESPECIAL DE AQUICULTURA E PESCA/PR',
       'PROCURADORIA GERAL DA FAZENDA NACIONAL',
       'SETORIAL ORCAMENTARIA E FINANCEIRA - ANM',
       'COORDENACAO-GERAL DO FUNDO DE TERRAS',
       'FDO EXERCITO - DIFERENCA CAMBIAL',
       'UNIVERSIDADE FEDERAL DO DELTA DO PARNAIBA',
       'COORDENACAO DE ORCAMENTO E FINANCAS - PRF',
       'TELECOMUNICACOES BRASILEIRAS S/A',
       'FUNDO NACIONAL DA CULTURA - FNC', 'UNIVERSIDADE FEDERAL DE JATAI',
       'UNIVERSIDADE FEDERAL DE RONDONOPOLIS',
       'UNIVERSIDADE FEDERAL DE CATALAO', 'MRE - DIFERENCA CAMBIAL'],
      dtype=object)

Vemos que todos los códigos y nombres vacios en las 2 primeras columnas se produce porque no hay ninguno de los dos datos rellenados, pero en organo y unidad gestora, vemos que no es así vamos a empezar por ahí.

Para corregirlo, vamos a generar un nuevo diccionario, pero esta vez usando los nombres como índices


In [5]:
datos = df.groupby("código del órgano")["nombre del órgano"].first()
lista_codigos = list(datos.index)
lista_names = list(datos.values)
diccionario_organos = {}
for i in range(0, len(lista_codigos)):
    diccionario_organos[lista_codigos[i]] = lista_names[i]  

diccionario_organos 

{20101.0: 'Presidência da República',
 20116.0: 'Fundo de Imprensa Nacional',
 20117.0: 'Fundo Nacional Antidrogas',
 20122.0: 'Secretaria Nacional de Políticas para Mulheres',
 20129.0: 'Secretaria Especial de Agricultura Familiar e do Desenvolvimento Agrário',
 20202.0: 'Fundação Escola Nacional de Administração Pública',
 20203.0: 'Agência Nacional do Cinema',
 20301.0: 'Comissão Nacional de Energia Nuclear',
 20302.0: 'Nuclebrás Equipamentos Pesados S.A.',
 20303.0: 'Indústrias Nucleares do Brasil',
 20402.0: 'Agência Espacial Brasileira',
 20403.0: 'Fundação Casa de Rui Barbosa',
 20404.0: 'Fundação Biblioteca Nacional',
 20408.0: 'Fundação Cultural Palmares',
 20411.0: 'Instituto do Patrimônio Histórico e Artístico Nacional',
 20412.0: 'Fundação Nacional de Artes',
 20415.0: 'Empresa Brasil de Comunicação',
 20501.0: 'Conselho Nacional de Desenvolvimento Científico e Tecnológico',
 20502.0: 'Financiadora de Estudos e Projetos',
 20603.0: 'Superintendência da Zona Franca de Manaus

Veamos los nulos antes de llamar a la función

In [6]:
nulos_codorg = df["código del órgano"].isnull().sum()
nulos_nameorg = df["nombre del órgano"].isnull().sum()
print(nulos_codorg)
print(nulos_nameorg)

1186
1302


Llamamos a la función que hemos creado para reemplazar nulos por valores válidos

In [7]:
fill_organo(df,diccionario_organos) #Pasamos el diccionario, para que si algún día se extiende 

In [8]:
nulos_codorg = df["código del órgano"].isnull().sum()
nulos_nameorg = df["nombre del órgano"].isnull().sum()
print(nulos_codorg)
print(nulos_nameorg)

905
905


In [9]:
condicion = df["código del órgano"].isnull()
df2 = df[condicion]
df2["nombre del órgano"].unique()

array([nan], dtype=object)

Ya hemos dejado los organos con nulos sólo si nombre y código es nulo, hagamos lo mismo con unidad gestora

In [10]:
datos = df.groupby("código de la unidad gestora")["nombre de la unidad gestora"].first()
lista_codigos2 = list(datos.index)
lista_names2 = list(datos.values)
diccionario2 = {}
for i in range(0, len(lista_codigos2)):
    diccionario2[lista_codigos2[i]] = lista_names2[i]    
    


In [11]:
nulos_codorg = df["código de la unidad gestora"].isnull().sum()
nulos_nameorg = df["nombre de la unidad gestora"].isnull().sum()
print(nulos_codorg)
print(nulos_nameorg)

1053
947


In [12]:
fill_unidad_gestora(df,diccionario2)

In [13]:
nulos_codorg = df["código de la unidad gestora"].isnull().sum()
nulos_nameorg = df["nombre de la unidad gestora"].isnull().sum()
print(nulos_codorg)
print(nulos_nameorg)

614
614


# Convertir los nulos en valores válidos

Ahora que ya tenemos esta parte, vamos a intentar convertir en valores válidos los nombres y códigos nulos de todas las columnas
Primero veamos si hay correlación 

In [14]:
condicion = df["código de la unidad gestora"].isnull()
df2 = df[condicion]
df2

código del órgano superior  \
74                          22000.0   
3831                        32000.0   
3855                        32000.0   
4423                        54000.0   
4427                        54000.0   
...                             ...   
1023953                     54000.0   
1025277                     54000.0   
1025568                     54000.0   
1025717                         NaN   
1026226                     20000.0   

                            nombre del órgano superior  código del órgano  \
74       Ministério da Agricultura, Pecuária e Abastec            22202.0   
3831                     Ministério de Minas e Energia            32205.0   
3855                     Ministério de Minas e Energia            32263.0   
4423                             Ministério do Turismo            20411.0   
4427                             Ministério do Turismo            20412.0   
...                                                ...                ...   
1023953                          Ministério do Turismo            34902.0   
1025277                          Ministério do Turismo            20404.0   
1025568                          Ministério do Turismo            20203.0   
1025717                                            NaN            20411.0   
1026226                       Presidência da República            20116.0   

                                         nombre del órgano  \
74             Empresa Brasileira de Pesquisa Agropecuária   
3831     Agência Nacional do Petróleo, Gás Natural e Bi...   
3855             Departamento Nacional de Produção Mineral   
4423     Instituto do Patrimônio Histórico e Artístico ...   
4427                            Fundação Nacional de Artes   
...                                                    ...   
1023953                          Fundo Nacional de Cultura   
1025277                       Fundação Biblioteca Nacional   
1025568                         Agência Nacional do Cinema   
1025717  Instituto do Patrimônio Histórico e Artístico ...   
1026226                         Fundo de Imprensa Nacional   

         código de la unidad gestora nombre de la unidad gestora  \
74                               NaN                         NaN   
3831                             NaN                         NaN   
3855                             NaN                         NaN   
4423                             NaN                         NaN   
4427                             NaN                         NaN   
...                              ...                         ...   
1023953                          NaN                         NaN   
1025277                          NaN                         NaN   
1025568                          NaN                         NaN   
1025717                          NaN                         NaN   
1026226                          NaN                         NaN   

                              categoría económica     origen de los ingresos  \
74                             Receitas Correntes  Outras Receitas Correntes   
3831                           Receitas Correntes  Outras Receitas Correntes   
3855                           Receitas Correntes  Outras Receitas Correntes   
4423                           Receitas Correntes        Receita de Serviços   
4427                           Receitas Correntes  Outras Receitas Correntes   
...                                           ...                        ...   
1023953                        Receitas Correntes        Receita Patrimonial   
1025277                        Receitas Correntes        Receita de Serviços   
1025568                        Receitas Correntes  Outras Receitas Correntes   
1025717                        Receitas Correntes        Receita de Serviços   
1026226  Receitas Correntes - intra-orçamentárias         Receita Industrial   

                                      tipo de ingresos  \
74                           Demai

In [15]:
df.groupby(["código del órgano", "código de la unidad gestora", "nombre de la unidad gestora"]).size().reset_index(name='counts').sort_values(by="código del órgano")



código del órgano  código de la unidad gestora  \
0              20101.0                     110005.0   
1              20116.0                     110245.0   
2              20117.0                     110246.0   
3              20122.0                     200021.0   
4              20129.0                     110690.0   
..                 ...                          ...   
363            74918.0                     533009.0   
364            74919.0                     537004.0   
365            81000.0                     810002.0   
366            90000.0                     390001.0   
367            91214.0                     913001.0   

                       nombre de la unidad gestora  counts  
0    SECRETARIA DE ADMINISTRACAO-SET.ORC.E FIN./PR    1548  
1      FUNDO DE IMPRENSA NACIONAL/EXEC.ORC.FINANC.    2937  
2                        FUNDO NACIONAL ANTIDROGAS      20  
3         SECRETARIA DE POLITICAS PARA AS MULHERES     166  
4     SEC.ESPEC.DE AGRIC.FAMIL.E DO DESENV.AGRARIO     472  
..                                             ...     ...  
363           FUNDO DE DESENVOLVIMENTO DO NORDESTE     502  
364       FUNDO DE DESENVOLVIMENTO DO CENTRO-OESTE     237  
365       SETORIAL ORCAMENTARIA E FINANCEIRA - MDH      15  
366                   RESERVA DE CONTINGENCIA/MEFP      25  
367                    AUTORIDADE PUBLICA OLIMPICA     147  

[368 rows x 4 columns]

In [16]:
c1 = df["código del órgano superior"] == 20000
cond = df["código del órgano"] == 67000 
a = df[c1]
a["código del órgano"].unique()

array([67000., 20101., 20116., 69000., 24208., 64000., 60000., 20117.,
       61000.,    nan])

In [17]:
c1 = df["código del órgano"] == 22202
cond = df["código del órgano"] == 67000 
a = df[c1]
a["código de la unidad gestora"].unique()

array([135037.,     nan])

In [18]:
c1 = df["código del órgano superior"] == 20000
cond = df["código del órgano"] == 20101 
a = df[cond]
a["código del órgano superior"].unique()

array([   nan, 20000.])

In [19]:
df2 = df[c1]
df2["código del órgano superior"].unique()

array([20000.])

In [20]:
diccionario_organo_unidad = df.groupby("código del órgano")["código de la unidad gestora"].first().dropna().to_dict()

In [21]:
cond = df["código del órgano superior"].isnull()
cond2 = df["código de la unidad gestora"].isnull()
df[cond & cond2]

código del órgano superior nombre del órgano superior  \
150126                          NaN                        NaN   
275212                          NaN                        NaN   
525593                          NaN                        NaN   
878054                          NaN                        NaN   
929868                          NaN                        NaN   
1025717                         NaN                        NaN   

         código del órgano                                  nombre del órgano  \
150126             26280.0        Fundação Universidade Federal de São Carlos   
275212             26263.0                     Universidade Federal de Lavras   
525593             26427.0                         Instituto Federal da Bahia   
878054             32396.0                      Agência Nacional de Mineração   
929868             25000.0  Ministério da Economia - Unidades com vínculo ...   
1025717            20411.0  Instituto do Patrimônio Histórico e Artístico ...   

         código de la unidad gestora nombre de la unidad gestora  \
150126                           NaN                         NaN   
275212                           NaN                         NaN   
525593                           NaN                         NaN   
878054                           NaN                         NaN   
929868                           NaN                         NaN   
1025717                          NaN                         NaN   

        categoría económica origen de los ingresos  \
150126   Receitas Correntes    Receita de Serviços   
275212   Receitas Correntes    Receita de Serviços   
525593   Receitas Correntes    Receita Patrimonial   
878054   Receitas Correntes    Receita de Serviços   
929868   Receitas Correntes          Contribuições   
1025717  Receitas Correntes    Receita de Serviços   

                                     tipo de ingresos  \
150126   Serviços Administrativos e Comerciais Gerais   
275212   Serviços Administrativos e Comerciais Gerais   
525593                            Valores Mobiliários   
878054   Serviços Administrativos e Comerciais Gerais   
929868                       Contribuições econômicas   
1025717  Serviços Administrativos e Comerciais Gerais   

                                               detalle  \
150126   INSCR.EM CONCURSOS E PROC.SELETIVOS-PRINCIPAL   
275212   SERVICOS DE INFORMACAO E TECNOLOGIA-PRINCIPAL   
525593    REMUNERACAO DE DEPOSITOS BANCARIOS-PRINCIPAL   
878054     SERV.ADMINISTRAT.E COMERCIAIS GERAIS-PRINC.   
929868   CONTR.S/REC.BRT EMP.PREST.SERV.TELECOM-PRINC.   
1025717    SERV.ADMINISTRAT.E COMERCIAIS GERAIS-PRINC.   

         valor previsto actualizado  valor registrado  valor ejecutado  \
150126                          0.0               0.0          1012.00   
275212                          0.0               0.0           427.50   
525593                          0.0               0.0            51.18   
878054                          0.0               0.0           626.39   
929868                          0.0               0.0          7921.96   
1025717                         0.0               0.0            74.00   

         porcentaje ejecutado fecha de registro  año fiscal  
150126                    0.0        2016-11-11        2016  
275212                    0.0        2017-02-17        2017  
525593                    0.0        2018-08-09        2018  
878054                    0.0        2020-02-20        2020  
929868                    0.0        2021-07-22        2021  
1025717                   0.0        2021-09-15        2021

# Que vamos a hacer
En funcion de lo anterior, nos fijamos que un código de órgano superior tiene múltiples códigos organo, si sacamos un diccionario de que códigos órgano apuntan a qué códigos organo superior podremos rellenar las columnas por código

Pero antes haremos lo mismo con el órgano y unidad gestora y ver si funciona

In [22]:
df.groupby("código de la unidad gestora")["código del órgano"].first().reset_index()

código de la unidad gestora  código del órgano
0                       110005.0            20101.0
1                       110008.0            58000.0
2                       110060.0            63000.0
3                       110101.0            60000.0
4                       110174.0            66000.0
..                           ...                ...
359                     773009.0            52233.0
360                     806001.0            25207.0
361                     810002.0            81000.0
362                     873001.0            52133.0
363                     913001.0            91214.0

[364 rows x 2 columns]

In [23]:
datos = df.groupby("código de la unidad gestora")["código del órgano"].first().sort_values()
lista_codigos4 = list(datos.index)
lista_names4 = list(datos.values)
diccionario4 = {}
for i in range(0, len(lista_codigos4)):
    diccionario4[lista_codigos4[i]] = lista_names4[i]    

datos = df.groupby("código del órgano")["nombre del órgano"].first()
lista_codigos = list(datos.index)
lista_names = list(datos.values)
diccionario_organos = {}
for i in range(0, len(lista_codigos)):
    diccionario_organos[lista_codigos[i]] = lista_names[i]  



In [24]:
nulos_codorg = df["código del órgano"].isnull().sum()
nulos_nameorg = df["nombre del órgano"].isnull().sum()
print(nulos_codorg)
print(nulos_nameorg)

905
905


In [25]:
fill_missing_organo(df,diccionario4,diccionario_organos)

In [26]:
nulos_codorg = df["código del órgano"].isnull().sum()
nulos_nameorg = df["nombre del órgano"].isnull().sum()
print(nulos_codorg)
print(nulos_nameorg)

0
0


In [27]:
c = df["nombre del órgano superior"].isnull()
df[c].head(1)

código del órgano superior nombre del órgano superior  código del órgano  \
31                         NaN                        NaN            22905.0   

                       nombre del órgano  código de la unidad gestora  \
31  Fundo de Defesa da Economia Cafeeira                     130137.0   

                     nombre de la unidad gestora categoría económica  \
31  FUNDO DE DEFESA DA ECON.CAFEEIRA/FUNCAFE/SPA  Receitas Correntes   

       origen de los ingresos                             tipo de ingresos  \
31  Outras Receitas Correntes  Indenizações, restituições e ressarcimentos   

                                         detalle  valor previsto actualizado  \
31  RECUPERACAO DE DESPESAS DE EXERC. ANTERIORES                     61810.0   

    valor registrado  valor ejecutado  porcentaje ejecutado fecha de registro  \
31               0.0              0.0                   0.0        2013-12-31   

    año fiscal  
31        2013

# Ha funcionado! 
Nos quedan 13 nulos que se debe a que estaban las 4 columnas en Null

Hagamos lo mismo para órgano superior con órgano

In [28]:
datos = df.groupby("código del órgano")["código del órgano superior"].first().sort_values()
lista_codigos3 = list(datos.index)
lista_names3 = list(datos.values)
diccionario3 = {}
for i in range(0, len(lista_codigos3)):
    diccionario3[lista_codigos3[i]] = lista_names3[i]    


In [29]:
nulos_codorg = df["código del órgano superior"].isnull().sum()
nulos_nameorg = df["nombre del órgano superior"].isnull().sum()
print(nulos_codorg)
print(nulos_nameorg)

10545
10545


In [30]:
fill_missing_organo_superior(df,diccionario3)

In [31]:
nulos_codorg = df["código del órgano superior"].isnull().sum()
nulos_nameorg = df["nombre del órgano superior"].isnull().sum()
print(nulos_codorg)
print(nulos_nameorg)

0
0


Ahora ya tenemos las 4 primeras columnas sin valores nulos, podemos convertir los datos a int

In [32]:
df["código del órgano superior"] = df["código del órgano superior"].astype(int)
df["código del órgano"] = df["código del órgano"].astype(int)

In [33]:
check_unidad_multiple_organos = df.groupby("código de la unidad gestora")["código del órgano"].nunique()
unidades_multiples_organos = check_unidad_multiple_organos[check_unidad_multiple_organos > 1]

# Mostrar las unidades gestoras que están vinculadas a más de un órgano (si existen)
print(unidades_multiples_organos)

código de la unidad gestora
307001.0    2
307002.0    2
410002.0    2
873001.0    2
Name: código del órgano, dtype: int64


In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1026299 entries, 0 to 1026298
Data columns (total 16 columns):
 #   Column                       Non-Null Count    Dtype  
---  ------                       --------------    -----  
 0   código del órgano superior   1026299 non-null  int64  
 1   nombre del órgano superior   1026299 non-null  object 
 2   código del órgano            1026299 non-null  int64  
 3   nombre del órgano            1026299 non-null  object 
 4   código de la unidad gestora  1025685 non-null  float64
 5   nombre de la unidad gestora  1025685 non-null  object 
 6   categoría económica          1007321 non-null  object 
 7   origen de los ingresos       987881 non-null   object 
 8   tipo de ingresos             994372 non-null   object 
 9   detalle                      996962 non-null   object 
 10  valor previsto actualizado   974984 non-null   float64
 11  valor registrado             999880 non-null   float64
 12  valor ejecutado              986834 non-null   

In [35]:
c = df["código de la unidad gestora"] == 873001
d2 = df[c]
d2.head(1)

código del órgano superior nombre del órgano superior  código del órgano  \
374                       52000       Ministério da Defesa              52133   

                                     nombre del órgano  \
374  Fundo de Desenvolvimento do Ensino Profissiona...   

     código de la unidad gestora  \
374                     873001.0   

                      nombre de la unidad gestora categoría económica  \
374  DIRETORIA DE FINANCAS-SISTEMA PARA O PAIS/MM  Receitas Correntes   

        origen de los ingresos                             tipo de ingresos  \
374  Outras Receitas Correntes  Indenizações, restituições e ressarcimentos   

                                          detalle  valor previsto actualizado  \
374  RECUPERACAO DE DESPESAS DE EXERC. ANTERIORES                         0.0   

     valor registrado  valor ejecutado  porcentaje ejecutado  \
374               0.0        658783.99                   0.0   

    fecha de registro  año fiscal  
374        2013-12-31        2013

# Clasificar facturas nulas como "sin información"

Para las columnas categoría económica, origen de los ingresos y tipo de ingresos vamos a cambiar los valores nulos por strings, vamos primero a comprobar como hacerlo



In [36]:
df["categoría económica"].isnull().sum()        #Sem informação


np.int64(18978)

In [37]:
df["origen de los ingresos"].isnull().sum() #Sem informação

np.int64(38418)

In [38]:
df["tipo de ingresos"].isnull().sum() # lo pasaremos a -> Sem informação

np.int64(31927)

In [39]:
# Reemplazar los valores nulos en las columnas especificadas por "Sem informação"
df["tipo de ingresos"] = df["tipo de ingresos"].fillna("Sem informação")
df["origen de los ingresos"] = df["origen de los ingresos"].fillna("Sem informação")
df["categoría económica"] = df["categoría económica"].fillna("Sem informação")


In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1026299 entries, 0 to 1026298
Data columns (total 16 columns):
 #   Column                       Non-Null Count    Dtype  
---  ------                       --------------    -----  
 0   código del órgano superior   1026299 non-null  int64  
 1   nombre del órgano superior   1026299 non-null  object 
 2   código del órgano            1026299 non-null  int64  
 3   nombre del órgano            1026299 non-null  object 
 4   código de la unidad gestora  1025685 non-null  float64
 5   nombre de la unidad gestora  1025685 non-null  object 
 6   categoría económica          1026299 non-null  object 
 7   origen de los ingresos       1026299 non-null  object 
 8   tipo de ingresos             1026299 non-null  object 
 9   detalle                      996962 non-null   object 
 10  valor previsto actualizado   974984 non-null   float64
 11  valor registrado             999880 non-null   float64
 12  valor ejecutado              986834 non-null   

# Eliminar columna detalle

Para nuestro análisis esta columna no nos va a proveer de información relevante 

In [41]:
df.drop(columns="detalle",inplace=True)


# Quitar valores nulos de valor previsto, registrado, ejecutado y porcentaje

Para obtener datos con sentido, haremos lo siguiente, si las columnas valor previsto, registrado, ejecutado son:
- Las tres nulas: Eliminaremos las filas, ya que no nos aportan nada de valor

El resto las tomaremos como son.

In [42]:
c = df["valor previsto actualizado"].isnull()
c1 = df["valor registrado"].isnull()
c2 = df["valor ejecutado"].isnull()
c3 = df["porcentaje ejecutado"].isnull()
df[c & c1 & c2 ].shape

(54, 15)

Tenemos 54 filas donde todo es nulo, las eliminamos para obtener mayor limpieza, además esto no afectará a los resultados

In [43]:
df.dropna(subset=["valor previsto actualizado", "valor registrado", "valor ejecutado"], how='all',inplace=True)


In [44]:
df[["valor previsto actualizado", "valor registrado", "valor ejecutado","porcentaje ejecutado"]] = df[["valor previsto actualizado", "valor registrado", "valor ejecutado","porcentaje ejecutado"]].fillna(0)
df[["valor previsto actualizado", "valor registrado", "valor ejecutado","porcentaje ejecutado"]] = df[["valor previsto actualizado", "valor registrado", "valor ejecutado","porcentaje ejecutado"]].astype(float)

Vemos ahora las que sean 0

In [57]:
c = df["valor previsto actualizado"] == 0
c1 = df["valor registrado"] == 0
c2 = df["valor ejecutado"] == 0 
c3 = df["porcentaje ejecutado"] == 0
df[c & c1 & c2 & c3].shape

(0, 15)

Tenemos otras 42715 Filas donde todo es 0, lo que no aporta nada a nuestros datos, las eliminaremos también

In [56]:
# Seleccionar las filas donde todas las columnas relevantes sean 0
condicion1 = df["valor previsto actualizado"] == 0
condicion2 = df["valor registrado"] == 0
condicion3 =  df["valor ejecutado"] == 0
condicion4 = df["porcentaje ejecutado"] == 0

df.drop(df[condicion1 & condicion2 & condicion3 & condicion4].index, inplace= True)


In [46]:
df["valor previsto actualizado"].isnull().sum()   

np.int64(0)

In [47]:
df["valor registrado"].isnull().sum()   

np.int64(0)

In [48]:
df["valor ejecutado"].isnull().sum()

np.int64(0)

In [49]:
df["porcentaje ejecutado"].isnull().sum()

np.int64(0)

# Ver y si fuera necesario, eliminar duplicados

Para ello vamos a dividir por órgano superior

In [50]:
df.duplicated().value_counts() 


False    999904
True      26341
Name: count, dtype: int64

In [51]:
# Filtrar las filas duplicadas (sin considerar el índice)
cond = df["año fiscal"] == 2013
df2 = df[cond]
duplicados = df2[df2.duplicated(keep=False)]

# Mostrar las filas duplicadas
duplicados


código del órgano superior nombre del órgano superior  \
679                        25000     Ministério da Economia   
712                        25000     Ministério da Economia   
837                        25000     Ministério da Economia   
890                        25000     Ministério da Economia   
923                        25000     Ministério da Economia   
1234                       25000     Ministério da Economia   
1292                       25000     Ministério da Economia   
1383                       25000     Ministério da Economia   
1464                       26000     Ministério da Educação   
1565                       26000     Ministério da Educação   
2002                       26000     Ministério da Educação   
2078                       26000     Ministério da Educação   
2088                       26000     Ministério da Educação   
2446                       26000     Ministério da Educação   
2490                       26000     Ministério da Educação   
2612                       26000     Ministério da Educação   
2793                       26000     Ministério da Educação   

      código del órgano                                  nombre del órgano  \
679               25000  Ministério da Economia - Unidades com vínculo ...   
712               25000  Ministério da Economia - Unidades com vínculo ...   
837               25000  Ministério da Economia - Unidades com vínculo ...   
890               25000  Ministério da Economia - Unidades com vínculo ...   
923               25000  Ministério da Economia - Unidades com vínculo ...   
1234              25000  Ministério da Economia - Unidades com vínculo ...   
1292              25000  Ministério da Economia - Unidades com vínculo ...   
1383              25000  Ministério da Economia - Unidades com vínculo ...   
1464              26276       Fundação Universidade Federal do Mato Grosso   
1565              26000  Ministério da Educação - Unidades com vínculo ...   
2002              26000  Ministério da Educação - Unidades com vínculo ...   
2078              26258         Universidade Tecnológica Federal do Paraná   
2088              26000  Ministério da Educação - Unidades com vínculo ...   
2446              26258         Universidade Tecnológica Federal do Paraná   
2490              26298      Fundo Nacional de Desenvolvimento da Educação   
2612              26276       Fundação Universidade Federal do Mato Grosso   
2793              26298      Fundo Nacional de Desenvolvimento da Educação   

      código de la unidad gestora  \
679                      170013.0   
712                      170013.0   
837                      170013.0   
890                      170013.0   
923                      170013.0   
1234                     170013.0   
1292                     170013.0   
1383                     170013.0   
1464                     154045.0   
1565                     150014.0   
2002                     150014.0   
2078                     153019.0   
2088                     150014.0   
2446                     153019.0   
2490                     153173.0   
2612                     154045.0   
2793                     153173.0   

                        nombre de la unidad gestora  categoría económica  \
679         SETORIAL ORCAMENTARIA E FINANCEIRA / ME   Receitas Correntes   
712         SETORIAL ORCAMENTARIA E FINANCEIRA / ME   Receitas Correntes   
837         SETORIAL ORCAMENTARIA E FINANCEIRA / ME   Receitas Correntes   
890         SETORIAL ORCAMENTARIA E FINANCEIRA / ME   Receitas Correntes   
923         SETORIAL ORCAMENTARIA E FINANCEIRA / ME   Receitas Correntes   
1234        SETORIAL ORCAMENTARIA E FINANCEIRA / ME   Receitas Correntes   
1292        SETORIAL ORCAMENTARIA E FINANCEIRA / ME   Receitas Correntes   
1383        SETORIAL ORCAMENTARIA E FINANCEIRA / ME   Receitas Correntes   
1464   FUNDACAO UNIVERSIDADE FEDERAL DE MATO GROSSO  Receitas de Capital   
1565  SUBSECRETARIA DE PLANEJ. E ORCAME